organization: hashi-demos-apj
workspace_name: vcs-aws-future-app
create_project: true
create_repo: false
project_name: Aarons VMware Project
file_triggers_enabled: false
workspace_auto_apply: true
create_variable_set: false
workspace_agents: true
execution_mode: agent
agent_pool_name: AaronPool
vcs_repo:
  identifier: hashi-demo-lab/vcs-aws-future-app
  branch: main
  ingress_submodules: null
  oauth_token_id: ot-EEzS6zKkh8tEBC7o