organization: hashi-demos-apj
workspace_name: vcs-azure-future-app-tafedemo
create_project: false
create_repo: false
project_name: Aarons Azure Projects
file_triggers_enabled: false
workspace_auto_apply: true
create_variable_set: false
execution_mode: agent
agent_pool_name: AaronPool
vcs_repo:
  identifier: hashi-demo-lab/vcs-azure-future-app
  branch: main
  ingress_submodules: null
  oauth_token_id: ot-EEzS6zKkh8tEBC7o