name: workspace-onboarding-api
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_DIRECTORY: ""
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  parse-workspace-config:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: get-workspace-yaml
        id: get-workspace
        run: |
          cd config
          echo $(ls *.yaml | jq -R . | jq -s .)
          echo "workspaces=$(echo $(ls *.yaml | jq -R . | jq -s .))" >> $GITHUB_OUTPUT
      - name: Echo-WORKSPACES
        run: echo "{{ steps.get-workspace.outputs.workspaces }}"
    outputs: 
        workspaces: ${{ steps.get-workspace.outputs.workspaces }}

  tfe-workspace:
    needs: parse-workspace-config
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        workspaces: ${{fromJson(needs.parse-workspace-config.outputs.workspaces)}}
    steps:
      - run: echo ${{ matrix.workspaces }}
        name: 
