name: workspace-onboarding-api
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_DIRECTORY: ""
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  parse-workspace-configuration:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: get workspace yaml
        run: |
          cd config
          echo $(ls *.yaml | jq -R . | jq -s .)
          echo "WORKSPACES=$(echo $(ls *.yaml | jq -R . | jq -s .))" >> $GITHUB_ENV
      - name: Echo WORKSPACES
        run: echo $WORKSPACES
    outputs:
      workspace-yaml: $WORKSPACES