name: workspace-onboarding-api
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_DIRECTORY: ""
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  parse-ws-config:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: get-workspace-yaml
        id: get-workspace
        run: |
          cd config
          echo $(ls *.yaml | jq -R . | jq -s .)
          echo "workspaces=$(echo $(ls *.yaml | jq -R . | jq -s .))" >> $GITHUB_OUTPUT
      - name: echo-workspaces
        run: echo "${{ steps.get-workspace.outputs.workspaces }}"
      - name: validate-yaml-map
        uses: mikefarah/yq@master
        with:
          cmd: yq --exit-status 'tag == "!!map"' ./config/*.yaml -v; 

    outputs: 
        workspaces: ${{ steps.get-workspace.outputs.workspaces }}

  tfe-ws-pre-reqs:
    needs: parse-ws-config
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        workspaces: ${{fromJson(needs.parse-ws-config.outputs.workspaces)}}
    steps:
      - name: echo-file
        run: echo ${{ matrix.workspaces }}
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: pretty-${{ matrix.workspaces }}
        uses: mikefarah/yq@master
        with:
          cmd: yq ./config/${{ matrix.workspaces }}
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
         python-version: '3.10'
         cache: 'pip'
      - name: install-python-dep
        run: pip install -r ./.github/workflows/requirements.txt
      - name: check-create-workspace
        run: python ./.github/workflows/test.py
