name: workspace-onboarding-api
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_DIRECTORY: ""
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  parse-ws-config:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: get-workspace-yaml
        id: get-workspace
        run: |
          cd config
          echo "workspaces="$(ls *.yaml | jq -R . | jq -s . | sed 's/.yaml//g')"" >> $GITHUB_OUTPUT
      - name: validate-yaml-map
        uses: mikefarah/yq@master
        with:
          cmd: yq --exit-status 'tag == "!!map"' ./config/*.yaml -v; 
    outputs: 
        workspaces: ${{ steps.get-workspace.outputs.workspaces }}

  tfe-ws-pre-reqs:
    needs: parse-ws-config
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        workspaces: ${{fromJson(needs.parse-ws-config.outputs.workspaces)}}
    steps:
      - name: echo-filename
        run: echo ${{ matrix.workspaces }}
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: log-${{ matrix.workspaces }}
        uses: mikefarah/yq@master
        with:
          cmd: yq ./config/${{ matrix.workspaces }}".yaml"
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
         python-version: '3.10'
         cache: 'pip'
      - name: install-python-dep
        run: pip install -r ./.github/workflows/requirements.txt
      - name: check-create-workspace
        run: python ./.github/workflows/test.py
        env:
          TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
          WORKSPACE_NAME: 'admin-ws-${{ matrix.workspaces }}'

  tfe-configversion:
    needs: [parse-ws-config, tfe-ws-pre-reqs]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        workspaces: ${{ fromJson(needs.parse-ws-config.outputs.workspaces) }}
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: Checkout tfc github-actions #only required whilst actions are private
        uses: actions/checkout@v3
        with:
          repository: hashicorp/tfc-workflows-github
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/tfc-workflows-github

      - name: Upload configuration version
        uses: ./.github/actions/tfc-workflows-github/actions/upload-configuration/
        id: tfe-configversion
        with:
          workspace: 'admin-ws-${{ matrix.workspaces }}'
          directory: ${{ env.TF_DIRECTORY }}
      
      - uses: cloudposse/github-action-matrix-outputs-write@main
        id: writeoutput
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.workspaces }}
          outputs: |-
            config: ${{ steps.tfe-configversion.outputs.configuration_version_id}}

  ## Read matrix outputs - this is using artifact until github supports
  rmatrix:
    runs-on: ubuntu-latest
    needs: [parse-ws-config, tfe-ws-pre-reqs, tfe-configversion]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: readmatrix
        with:
          matrix-step-name: "tfe-configversion"
    outputs:
      result: "${{ steps.readmatrix.outputs.result }}"

  tfe-ws-run-plan:
    needs: [parse-ws-config, tfe-ws-pre-reqs, tfe-configversion, rmatrix]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        workspaces: ${{ fromJson(needs.parse-ws-config.outputs.workspaces) }}
    steps:
      - name: output_results
        env:
          OUTPUT1: ${{ needs.rmatrix.outputs.result }}
        run: echo "$OUTPUT1"
        
      - name: checkout-repo
        uses: actions/checkout@v3
        id: checkout

      - name: Checkout tfc github-actions #only required whilst actions are private
        uses: actions/checkout@v3
        with:
          repository: hashicorp/tfc-workflows-github
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/tfc-workflows-github